

spring:
  cloud:
    gateway:
      routes:
       - id : registration-service-route
         uri: lb://customer-service
         predicates:
          - Path=/api/v1/customer/registration
          - Path=/api/v1/confirm-account
server:
  port: 8989